apiVersion: v1
kind: Service
metadata:
  name: service-external-ips
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 1.2.3.4
