apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-cluster-ip
  name: service-cluster-ip
spec:
  type: ClusterIP
  ports:
  - name: http-port
    port: 80
    # containerPort or port name.
    targetPort: http-port
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.15-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: 10m
        ports:
        - name: http-port
          containerPort: 80
          protocol: TCP
