apiVersion: v1
kind: Service
metadata:
  name: service-proxy-external
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: service-proxy-external
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.5.216
    ports:
    - name: http
      port: 80
         
