apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: z-server
  namespace: default
spec:
  rules:
    - host: ingress-nginx.z.io
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
    - host: httpbin.z.io
      http:
        paths:
          - backend:
              serviceName: service-external-name
              servicePort: 80
            path: /
